### ISSUE TITLE
Relax constraint: Allow data table re-upload if column types differ

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#49]
The requirement for column types to be consistent is too restrictive. One of the most common reasons to "re-upload" with different column types occurs when the original upload has character type columns that should be numeric (i.e. numeric columns containing character strings other than defined missing value codes). Currently, these columns will be detected as numeric by ezEML and re-upload will fail.

A solution could be for the re-uploaded table to inherit the types specified in the original. A user can then edit the types using the change type feature for the relevant columns.

In some sense this issue is more of a bug than an expected feature since it prioritizes ezEML's type detection algorithm over the users expertise and intent.

**Comment by clnsmth** [comment]
Can't get around this by uploading the fixed table as "new" then importing the column properties from the original either.

**Comment by clnsmth** [comment]
Just ran into this issue again for the use case listed above.

**Comment by jon-ide** [comment]
Fixed in release 2021.08.09. A column's type is allowed to differ, in which case the new column type is used. So, for example, in the case where the column originally was classified as text because some text values were present, but the re-uploaded table has been corrected to be numerical, the column will be classified as numerical after re-upload and the metadata will be modified accordingly. The user will see a message that says which columns have changed type. For example, 
![image](https://user-images.githubusercontent.com/32145835/128751843-38773446-1732-46f3-a40f-e624bdaed216.png)
