### ISSUE TITLE
Method Step Instrumentation field: unexpected behavior 

### ISSUE THREAD

**Issue by alfalimajuliett** [PASTAplus/ezEML#95]
The Instrumentation field in the exEML browser interface is not reflecting changes after 'save and continue' is selected, however, it creates a new instrumentation element in the .xml file each time the Method Step is opened and saved in the interface, regardless of if changes are made. For example, attempting to update the name of an instrument did not appear on the ezEML interface, but produced this result in the xml:

```
<methodStep>
        <description>          <para>For each surveyed tree, we registered height (in meters) based on the Forestry Pro II when possible. When the crown was covered and the accurate use of the Forestry Pro II was not possible, we used the distance laser to measure the height as high as possible, and visually estimate the remaining height based on a comparison of measured neighboring trees.</para>
</description>
        <instrumentation>Forestry-pro II</instrumentation>
        <instrumentation>Forestry Pro II and laser</instrumentation>
        <instrumentation>Forestry-pro II</instrumentation>
      </methodStep>
```

**Comment by jon-ide** [comment]
Fixed in release 2023.01.04. Thanks very much for reporting the issue.

In the process of fixing it, I noticed that the EML standard allows multiple instrumentation elements for a methodStep, but the ezEML UI does not support displaying multiple instrumentation elements. If a package has multiple instrumentation elements (either because the package was created outside of ezEML or was created while this bug existed), the instrumentation descriptions are now collected into a single instrumentation element, with the descriptions separated by newlines. When the EML for the package is created, it will have a single instrumentation element for that methodStep, containing the list of instrumentation descriptions. 

ezEML cannot automatically clean up the cases that were created while the bug existed, because it cannot know whether or not the user intended to have multiple instrumentation elements. The user will now be able to edit the list of instrumentation descriptions, however, and save the corrected version.
